<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class FlipCardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('letters')->insert([
            'letter'=>'A',
            'type'=>'vowel',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/A_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'B',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/B_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'C',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/C_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'CH',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/CH_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'D',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/D_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'E',
            'type'=>'vowel',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/E_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'F',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/F_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'G',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/G_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'H',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/H_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'I',
            'type'=>'vowel',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/I_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'J',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/J_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'K',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/K_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'L',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/L_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'LL',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/LL_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'M',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/M_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'N',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/N_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'Ñ',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/N2_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'O',
            'type'=>'vowel',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/O_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'P',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/P_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'Q',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/Q_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'R',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/R_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'S',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/S_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'T',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/T_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'U',
            'type'=>'vowel',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/U_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'V',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/V_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'W',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/W_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'X',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/X_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'Y',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/Y_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'Z',
            'type'=>'consonant',
            'sound'=>'',
            'video'=>'https://play.micukids.com/play/flipcards/back/Z_animation.mp4'
            ]);
            }}