<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class FlipCardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('letters')->insert([
            'letter'=>'A',
            'type'=>'vowel',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com/play/flipcards/back/A_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'B',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/B_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'C',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com/play/flipcards/back/C_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'CH',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com/play/flipcards/back/CH_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'D',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com/play/flipcards/back/D_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'E',
            'type'=>'vowel',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com/play/flipcards/back/E_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'F',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com/play/flipcards/back/F_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'G',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/G_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'H',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/H_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'I',
            'type'=>'vowel',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/I_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'J',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/J_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'K',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/K_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'L',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/L_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'LL',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/LL_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'M',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/M_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'N',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/N_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'Ñ',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/N2_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'O',
            'type'=>'vowel',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/O_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'P',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/P_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'Q',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/Q_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'R',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/R_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'S',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/S_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'T',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/T_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'U',
            'type'=>'vowel',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/U_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'V',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/V_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'W',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/W_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'X',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/X_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'Y',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/Y_animation.mp4'
            ]);
        DB::table('letters')->insert([
            'letter'=>'Z',
            'type'=>'consonant',
            'Upper'=>true,
            'sound'=>'',
            'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/Z_animation.mp4'
            ]);

            DB::table('letters')->insert([
                'letter'=>'a',
                'type'=>'vowel',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/A_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'b',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/B_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'c',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/C_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'ch',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/CH_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'d',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/D_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'e',
                'type'=>'vowel',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/E_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'f',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/F_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'g',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/G_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'h',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/H_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'i',
                'type'=>'vowel',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/I_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'j',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/J_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'k',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/K_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'l',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/L_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'m',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/M_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'n',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/N_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'ñ',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/N2_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'o',
                'type'=>'vowel',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/O_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'p',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/P_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'q',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/Q_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'r',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/R_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'s',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/S_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'t',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/T_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'u',
                'type'=>'vowel',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/U_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'v',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/V_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'w',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/W_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'x',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/X_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'y',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/Y_animation.mp4'
                ]);
            DB::table('letters')->insert([
                'letter'=>'z',
                'type'=>'consonant',
                'Upper'=>false,
                'sound'=>'',
                'video'=>'play.micukids.com@play.micukids.com/play/flipcards/back/Z_animation.mp4'
                ]);
    }
}
